apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1"
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    deployment:
      kind: DaemonSet
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    # no load balancer
    service:
      enabled: false

    # use host network for directly port listening
    hostNetwork: true

    ports:
      web:
        port: 80
        expose: true
        protocol: TCP
        exposePort: 80
        redirectTo:
          port: websecure
      websecure:
        port: 443
        expose: true
        protocol: TCP
        exposePort: 443
        tls:
          enable: true
      metrics:
        port: 9101
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0

    # run as root to 80 and 443 port listen permission
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
    podSecurityContext:
      fsGroup: 0
