apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redis
  name: redis-config-map
data:
  redis-config:  |
    bind 0.0.0.0
    maxmemory 4gb
    maxmemory-policy allkeys-lru
    requirepass "passwd"